#!/usr/bin/with-contenv sh

exec env SPARK_WORKER_CORES=1 SPARK_WORKER_MEMORY=1g /opt/spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://$HOSTNAME:7077
