#!/usr/bin/with-contenv sh

echo "spark.master  spark://$HOSTNAME:7077" > /opt/spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/conf/spark-defaults.conf

exec /opt/spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/bin/spark-class org.apache.spark.deploy.master.Master --ip $HOSTNAME --port 7077 --webui-port 8080
